# SwiftLint Configuration
# For documentation: https://realm.github.io/SwiftLint/

# Included file patterns
included:
  - ExpenseTracker
  - ExpenseTrackerTests
  - ExpenseTrackerUITests

# Excluded file patterns
excluded:
  - .build
  - .swiftpm
  - Pods
  - Carthage
  - Build
  - DerivedData

# Rules configuration
# Identifiers
identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - id
    - x
    - y
    - z

# Line length
line_length:
  warning: 120
  error: 200

# File length
file_length:
  warning: 400
  error: 600

# Type body length
type_body_length:
  warning: 350
  error: 500

# Trailing whitespace
trailing_whitespace: error

# Trailing newline
trailing_newline: error

# Function body length
function_body_length:
  warning: 50
  error: 100

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting (avoid deeply nested code)
nesting:
  type_level: 2
  function_level: 2

# Complexity metrics
large_tuple:
  warning: 3

disabled_rules:
  - todo  # Allow TODOs in code
  - vertical_whitespace  # Too strict
  - switch_case_on_newline  # Too strict for single-case switches
  - nesting  # Too strict for view compositions
  - naming_patterns  # Disable pattern matching, use explicit rules

opt_in_rules:
  - empty_count
  - explicit_init

# Reporter
reporter: "xcode"
