name: iOS Build (basic)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15   # macOS runner with Xcode preinstalled

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'   # pick an installed version

      - name: Build with xcodebuild
        run: |
          set -o pipefail
          xcodebuild \
            -project ExpenseTracker.xcodeproj \
            -scheme ExpenseTracker \
            -destination 'generic/platform=iOS Simulator' \
            build
