name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ios-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: macos-15            # pin a macOS that carries Xcode 16.x
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.x
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'   # or '16.2' or '16.*'

      - name: Show Xcode / SDK info
        run: |
          xcode-select -p
          xcodebuild -version
          xcodebuild -showsdks

      - name: Show available destinations
        run: |
          echo "Available destinations:"
          xcodebuild -showdestinations -project ExpenseTracker.xcodeproj -scheme ExpenseTracker
          
      - name: Set simulator destination
        run: |
          echo "DEST=generic/platform=iOS Simulator" >> $GITHUB_ENV
          echo "Using generic iOS Simulator destination"

      - name: Build & Test (with result bundle)
        if: ${{ env.DEST != '' }}
        id: test
        timeout-minutes: 20
        shell: bash
        run: |
          set -o pipefail
          mkdir -p build
          
          echo "Using destination: $DEST"
          
          xcodebuild \
            -project ExpenseTracker.xcodeproj \
            -scheme ExpenseTracker \
            -sdk iphonesimulator \
            -destination "$DEST" \
            -configuration Debug \
            -enableCodeCoverage YES \
            -resultBundlePath build/ExpenseTracker.xcresult \
            test | tee build/xcodebuild.log
          echo "result_bundle=build/ExpenseTracker.xcresult" >> $GITHUB_OUTPUT

      - name: Upload result bundle & logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcresult-and-logs
          path: |
            build/ExpenseTracker.xcresult
            build/xcodebuild.log
          retention-days: 7
          if-no-files-found: warn

      - name: Clean up simulators
        if: always()
        run: |
          xcrun simctl shutdown all || true
          pkill -9 -f Simulator || true