name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ios-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: macos-15            # pin a macOS that carries Xcode 16.x
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.x
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'   # or '16.2' or '16.*'

      - name: Show Xcode / SDK info
        run: |
          xcode-select -p
          xcodebuild -version
          xcodebuild -showsdks

      - name: Show available destinations
        run: |
          echo "Available destinations:"
          xcodebuild -showdestinations -project ExpenseTracker.xcodeproj -scheme ExpenseTracker
          
      - name: Set simulator destination
        run: |
          echo "DEST=platform=iOS Simulator,name=iPhone SE (3rd generation)" >> $GITHUB_ENV
          echo "Using iPhone SE (3rd generation) simulator"

      - name: Build Only (reliable)
        timeout-minutes: 10
        run: |
          xcodebuild \
            -project ExpenseTracker.xcodeproj \
            -scheme ExpenseTracker \
            -sdk iphonesimulator \
            -configuration Debug \
            build

      - name: Upload result bundle & logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcresult-and-logs
          path: |
            build/ExpenseTracker.xcresult
            build/xcodebuild.log
          retention-days: 7
          if-no-files-found: warn

      - name: Clean up simulators
        if: always()
        run: |
          xcrun simctl shutdown all || true
          pkill -9 -f Simulator || true