- name: Build for testing (no sim boot)
  run: |
    set -o pipefail
    xcodebuild build-for-testing \
      -project ExpenseTracker.xcodeproj \
      -scheme ExpenseTracker \
      -destination 'generic/platform=iOS Simulator' \
      -configuration Debug
