# .github/workflows/ios-2.yml
name: iOS Build (build-for-testing)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      - name: Build for testing (no sim boot)
        run: |
          set -o pipefail
          xcodebuild build-for-testing \
            -project ExpenseTracker.xcodeproj \
            -scheme ExpenseTracker \
            -destination 'generic/platform=iOS Simulator' \
            -configuration Debug
