name: iOS Build (build-for-testing only)

on:
  pull_request: { branches: [ main ] }
  push: { branches: [ main ] }

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with: { xcode-version: '16.2.0' }
      - name: Build for testing (no sim boot)
        run: |
          set -o pipefail
          xcodebuild build-for-testing \
            -project ExpenseTracker.xcodeproj \
            -scheme ExpenseTracker \
            -destination 'generic/platform=iOS Simulator' \
            -configuration Debug
